/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#516b4c",
        "on-secondary-fixed": "#092008",
        "background": "#fff8f0",
        "on-background": "#1e1b16",
        "on-tertiary-fixed-variant": "#653d1e",
        "on-primary-container": "#6a3930",
        "on-tertiary-fixed": "#301400",
        "surface": "#fff8f0",
        "inverse-primary": "#fbb6a8",
        "tertiary-container": "#e1aa82",
        "on-surface-variant": "#524341",
        "primary-fixed": "#ffdad3",
        "tertiary-fixed": "#ffdcc5",
        "surface-container-highest": "#e8e2d8",
        "secondary-fixed": "#cdebc4",
        "surface-variant": "#e8e2d8",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#351009",
        "primary-container": "#e8a598",
        "surface-container": "#f4ede3",
        "on-primary": "#ffffff",
        "surface-container-low": "#faf3e9",
        "surface-dim": "#e0d9d0",
        "on-tertiary-container": "#653e1e",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#6a3930",
        "error-container": "#ffdad6",
        "secondary-container": "#cdebc4",
        "tertiary-fixed-dim": "#f4bb92",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#b1cfa9",
        "primary": "#865046",
        "secondary": "#4b6546",
        "outline": "#847370",
        "surface-bright": "#fff8f0",
        "on-surface": "#1e1b16",
        "surface-container-high": "#eee7dd",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#fbb6a8",
        "inverse-surface": "#33302a",
        "inverse-on-surface": "#f7f0e6",
        "tertiary": "#805533",
        "on-secondary-fixed-variant": "#344d30",
        "surface-tint": "#865046",
        "on-secondary": "#ffffff",
        "outline-variant": "#d7c2be",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1100px",
        "pixel-unit": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "body-lg": ["DM Sans", "sans-serif"],
        "headline-lg-mobile": ["Anybody", "sans-serif"],
        "headline-lg": ["Anybody", "sans-serif"],
        "headline-md": ["Anybody", "sans-serif"],
        "label-sm": ["Anybody", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "label-lg": ["Anybody", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "20px",
          { lineHeight: "28px", fontWeight: "800" },
        ],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-1px", fontWeight: "800" },
        ],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "12px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "16px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
